//Rozszerzmy naszą aplikację z zadania 6 o dodatkowe działania matematyczne takie jak mnożenie,
//dzielenie i odejmowanie.Podzielmy zadania na odpowiednie ścieżki.
// /mnozenie...
// /dzielenie...
// /dodawanie...
// /odejmowanie...
// Gdy działanie jest niemożliwe do wykonania, aplikacja powinna zwracać odpowiedni komunikat
// oraz kod statusu Bad Request
